### PR TITLE
Fix invalid state error when using React.StrictMode

### LINKED ISSUE #13: Invalid State
I am getting an Invalid state when following the documentation. Here is what I have for my code:

image

App.tsx
```typescript
const auth0 = new Auth0Client({
  domain: import.meta.env.VITE_AUTH0_DOMAIN,
  clientId: import.meta.env.VITE_AUTH0_CLIENT_ID,
  cacheLocation: "localstorage",
  authorizationParams: {
    audience: import.meta.env.VITE_AUTH0_AUDIENCE,
  },
});

const authProvider = Auth0AuthProvider(auth0, {
  loginRedirectUri: import.meta.env.VITE_LOGIN_REDIRECT_URL,
  logoutRedirectUri: import.meta.env.VITE_LOGOUT_REDIRECT_URL,
});

export const App = () => (
  <BrowserRouter>
    <Admin authProvider={authProvider} dashboard={Dashboard}>
      <Resource name="Billing Transactions"></Resource>
    </Admin>
  </BrowserRouter>
);

```

.env
```
VITE_AUTH0_DOMAIN="asdfasdf.us.auth0.com"
VITE_AUTH0_CLIENT_ID="asdfasdf"
VITE_AUTH0_AUDIENCE="https://asdfasdf.us.auth0.com/api/v2/"
VITE_LOGIN_REDIRECT_URL="https://mywebsite.com/auth-callback"
VITE_LOGOUT_REDIRECT_URL="https://mywebsite.com"
```

Auth0 Application URIs
```
Application Login URI: Blank
Allowed Callback URLs: https://mywebsite.com/auth-callback
Allowed Logout URLs: https://mywebsite.com
Allowed Web Origins: https://mywebsite.com
Allow Cross-Origin Authentication: https://mywebsite.com
```

### PR DESCRIPTION
**Pull request by djhi**
May fix #13 too.

### CODE REVIEW

**Review by slax57 — APPROVED** [review]

File: packages/ra-auth-auth0/src/authProvider.ts [hunk 1]
```diff
@@ -138,15 +138,27 @@ export const Auth0AuthProvider = (
...
-        if (query.includes('code=') && query.includes('state=')) {
-            try {
-                await client.handleRedirectCallback();
-                return;
-            } catch (error) {
-                throw { redirectTo: false, message: error.message };
-            }
+        if (!handleCallbackPromise) {
+            handleCallbackPromise = new Promise(async (resolve, reject) => {
+                const query = window.location.search;
```
Comment (fzaninotto) [inline packages/ra-auth-auth0/src/authProvider.ts:143]: Since the Promise is cached, it won't detect any change in `window.location.search`. So e.g. when accepting an email invite that expired, and trying a second invite, the user won't be able to log in.

Comment (fzaninotto) [reply packages/ra-auth-auth0/src/authProvider.ts:143]: can't you use a debounce instead?

Comment (slax57) [reply packages/ra-auth-auth0/src/authProvider.ts:143]: It's cached as long as the `authProvider.ts` source code is in memory, but to get on the `/auth-callback` page you have to come from the Auth0 website, so there is no way the promise will still be in memory. If ever you switch user, you have to navigate to Auth0's website at some point which will unload `authProvider.ts`, so this shouldn't be an issue either.
