### PR TITLE
Fix callback issues

### LINKED ISSUE #4: Infinite loop after login
Keep getting sent around in circles after logging in: http://127.0.0.1:5173/auth-callback keeps getting called.

In `checkAuth` `client.isAuthenticated()` returns false - even though I am logged in?

### PR DESCRIPTION
**Pull request by djhi**
Fixes #4

### CODE REVIEW

File: packages/ra-auth-auth0/src/authProvider.ts [hunk 1]
```diff
@@ -141,8 +142,7 @@ export const Auth0AuthProvider = (
                 await client.handleRedirectCallback();
                 return;
             } catch (error) {
-                console.log('error', error);
-                throw error;
+                throw { redirectTo: false };
```
Comment (slax57) [inline packages/ra-auth-auth0/src/authProvider.ts]: why not return also the error message, so that it can be displayed in the AuthCallback page?

**Review by slax57 — APPROVED** [review]
