### PR TITLE
Fix `checkAuth` should reject when `redirectOnCheckAuth` is set to `false`

### LINKED ISSUE #3: checkAuth should throw an error after the redirect
At the moment, the `checkAuth` function just redirects, but does not actually return a rejected promise. This often seems to work fine, but it can lead to issues, because under certain conditions, the code continues to execute even after the redirect has started. For example, using `requireAuth` does not work properly in this case, because it `checkAuth` just returns normally, so it is assumed that the user is authenticated.

Even worse, this can lead to `checkAuth` being called again (resulting in a new login attempt), if that is required by specific routes. And even `checkError` might be called, because we a re not authenticated yet, but some routes might result in backend calls.

Combined, this can result in extremely nasty race conditions, where the login sometimes works, and sometimes doesn't, depending on when the browser decides to stop the execution of JavaScript when the redirect happens. This can also differ between browsers. I don't have any resources, but from my experience, Firefox tends to continue executing JavaScript for longer than Chrome, so the problems are more likely to manifest there.

Also, at the moment, `checkAuth` doesn't do anything if the `redirectOnCheckAuth` option is set to `false`.

In total, I would recommend to add a simple `throw new Error()` at the end of `checkAuth`, to handle both the problem after the redirect and the `redirectOnCheckAuth === false` case properly.

### PR DESCRIPTION
**Pull request by djhi**
Fix #3

### CODE REVIEW

File: packages/ra-auth-auth0/src/authProvider.ts [hunk 1]
```diff
@@ -108,6 +108,7 @@ export const Auth0AuthProvider = (
                 },
             });
         }
+        return Promise.reject();
```
Comment (fzaninotto) [inline packages/ra-auth-auth0/src/authProvider.ts]: `throw` would be more correct here as you're in an `async` function.

**Review by fzaninotto — APPROVED** [review]
